### ISSUE TITLE
Referencing a struct within a range

### ISSUE THREAD

**Issue by sebastiandeutsch** [yosssi/ace#42]
I'm ranging over a slice but I want to enable some functions if the object is accessible by the currently logged in user (just visually).

    <% range .Projects %>
        ...
        <% if eq .CurrentUser.Id .User.Id %>
           ...
        <% end %>
    <% end %>

This gives me this error:

    template: views/base:views/application/index:1:436: executing "views/application/index::main" at <.CurrentUser.Id>: CurrentUser is not a field of struct type models.Project

Question: How do I refence a variable that is outside of the range scope? Or how could I implement the desired behaviour?

**Comment by sebastiandeutsch** [comment]
Figured it out by myself - assigning variables is the key:

    <% $CurrentUserId := .CurrentUser.Id %>
    <% range $project := .Projects %>
        ...
        <% if $CurrentUserId %>
            <% if eq $CurrentUserId $project.User.Id %>
                a href="/projects/<% $project.Id%>/delete" Delete
            <% end %>
        <% end %>
    <% end %>

**Comment by yosssi** [comment]
@sebastiandeutsch I'm so sorry for the late reply. Yes, you can use variables in the range loop. Thanks for using Ace template engine. I'm very glad to see that you're using this template engine!

**Comment by sebastiandeutsch** [comment]
Thanks for your very nice templating engine. Seeing all the other options I like Ace the most. Btw: My Repo is public: http://golangtoolbox.com but I've seen that you already forked it :-) Feel free to code review and improve things. Maybe it can be a nice showcase.
