### ISSUE TITLE
The API is complicated.

### ISSUE THREAD

**Issue by omeid** [yosssi/ace#43]
First of all, thanks a lot for this package, as someone who really likes Jade I totally appreciate this project.

But the current API is over complicated. A similar api to the original `http/template` would be great, or at least something with the similar level of abstraction.

If I want to compile a template, I just want.

``` go
ace.Compile([]byte, map[string][]byte) *html.Template
```

And I would be happy.

And when working with Go templates, something like this would be ideal.

``` go
ace.Template(*template.Template, string. []byte)
```

And I would be happy if you parsed/compiled my `[]byte` and stick it in the `template.Temlate` under the name supplied by `string`.

Of course, the `map[string][]bytes` holds the includes.

**Comment by yosssi** [comment]
I'm so sorry for the late reply. I'll think about it later. Thanks!

**Comment by omeid** [comment]
Not a problem. I managed to [get it working](https://github.com/slurp-contrib/ace/blob/master/ace.go#L30-L73) but it is far more cumbersome, than for example how [gcss](https://github.com/slurp-contrib/gcss/blob/master/gcss.go#L26-L33) is handled.

**Comment by omeid** [comment]
Any updates on this?

**Comment by robsaunders** [comment]
I completely agree - file streams or a byte buffer is all that's needed - why does the library need to know about file locations? They should be available convenience wrappers over the top of the library but they seem to go right down to the core. Imo an API clean up would require a complete rewrite as it seems to be threaded all throughout the library.

@yosssi your gcss library as infinitely cleaner, as it just takes an io.Reader and io.Writer object, basically what @omeid suggested, I'm wondering why the change in style for ace? Perhaps it's an older project?
