### ISSUE TITLE
Create 0.0.5 tag

### ISSUE THREAD

**Issue by olivierlemasle** [yosssi/ace#75]
Hello,

Would it be possible to release a new tag for this library? Ace API has evolved significantly since tag 0.0.4 in 2014.

To give you more context, we'd like to package this library for Fedora. However, as the static site generator Hugo depends on commit ea038f4 of ace (cf. https://github.com/spf13/hugo/blob/ea165bf/vendor/vendor.json#L328), we'd like to package a recent release of the library.
Specifically,  Hugo uses ace.CompileResultWithTemplate which is not available in the latest tag 0.0.4.

Thank you!

**Comment by yosssi** [comment]
@olivierlemasle Released v0.0.5: https://github.com/yosssi/ace/releases/tag/v0.0.5
Thanks.

**Comment by olivierlemasle** [comment]
Thank you @yosssi

**Comment by olivierlemasle** [comment]
Hi @yosssi 
Just to let you know that as I told you above, this library is now packaged in Fedora repositories (cf. https://admin.fedoraproject.org/pkgdb/package/rpms/golang-github-yosssi-gohtml/).

Thanks for this project!
